const { Event } = require('../models');

const eventEl = [
    {
        name: "Deep, Dark, and Dangerous",
        date: "2023-02-16",
        time_start: "14:00:00",
        est_length: 150,
        is_public: true,
        is_virtual: false,
        max_users: 8,
        location: "123 Main St. Fort Collins, CO 80525",
        category: "Campaign/Legacy",
        game_name: "Gloomhaven",
        notes: "Hosting up to two games depending on attendance. Typical length is 2 hours. BYOB!"
    },
    {
        name: "Wednesday Night Draft",
        date: "2023-02-01",
        time_start: "19:30:00",
        est_length: 240,
        is_public: true,
        is_virtual: false,
        max_users: 20,
        location: "1119 W Drake Rd C-30, Fort Collins, CO 80526",
        category: "Deck Construction",
        game_name: "Magic: The Gathering",
        notes: "Entrance cost is $10. All ages welcome."
    }, 
    {
        name: "Saturday Smash Suite",
        date: "2023-04-01",
        time_start: "12:00:00",
        est_length: 270,
        is_public: true,
        is_virtual: true,
        max_users: 32,
        location: "smash.gg",
        category: "Video Game",
        game_name: "Super Smash Bros. Ultimate",
        notes: "Double Elimination Tournament. 3 Stocks, 8 Minutes, No Hazards."
    },
    {
        name: "Does Anyone Have Any Sheep?",
        date: "2023-02-08",
        time_start: "18:30:00",
        est_length: 150,
        is_public: false,
        is_virtual: false,
        max_users: 4,
        location: "4600 Jason St, Denver, CO 80211",
        category: "Eurogame",
        game_name: "Settlers of Catan",
        notes: "Snacks and beer will be provided, just bring smiles!"
    },
    {
        name: "Venture Capitalists",
        date: "2023-02-13",
        time_start: "10:00:00",
        est_length: 180,
        is_public: false,
        is_virtual: false,
        max_users: 8,
        location: "1418 W Howard St, Chicago, IL 60626",
        category: "Roll-and-Move",
        game_name: "Monopoly",
        notes: "Get ready to wreck our friendship in this extremely competetive game of Monopoly"
    },
    {
        name: "Old School Gamerz Only",
        date: "2023-02-08",
        time_start: "22:00:00",
        est_length: 120,
        is_public: true,
        is_virtual: false,
        max_users: 6,
        location: "",
        category: "Wargame",
        game_name: "Warhammer 40,000 (1998)",
        notes: "Playing old school 40k. Beverages supplied."
    },
    {
        name: "Cyber DnD",
        date: "2023-05-01",
        time_start: "12:00:00",
        est_length: 240,
        is_public: true,
        is_virtual: true,
        max_users: 6,
        location: "roll20.net",
        category: "Campaign/Legacy",
        game_name: "Dungeons and Dragons",
        notes: "Welcoming new players."
    },
    {
        name: "Spice Traders Anonymous",
        date: "2023-04-20",
        time_start: "15:00:00",
        est_length: 180,
        is_public: false,
        is_virtual: false,
        max_users: 6,
        location: "1119 W Drake Rd C-30, Fort Collins, CO 80526",
        category: "Area Control",
        game_name: "Dune (2019)",
        notes: "Casual game night with some friends."
    },
    {
        name: "Who Done It?",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    },
    {
        name: "",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    },
    {
        name: "",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    },
    {
        name: "",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    },
    {
        name: "",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    },
    {
        name: "",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    },
    {
        name: "",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    },
    {
        name: "",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    },
    {
        name: "",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    },
    {
        name: "",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    },
    {
        name: "",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    },
    {
        name: "",
        date: "",
        time_start: "",
        est_length: ,
        is_public: ,
        is_virtual: ,
        max_users: ,
        location: "",
        category: "",
        game_name: "",
        notes: ""
    }
]

const eventData = () => Event.bulkCreate(eventData);

module.exports = eventData;